name: Linux Kernel Builds

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 04 * * 6"
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: ARM64
        run: |
          bash setup.sh ARM64
          
  build-arm:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ARM
        run: |
          bash setup.sh ARM

  build-x86:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-projects/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: X86_64
        run: |
          bash setup.sh X86
